steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - bss-etl
      - --gen2
      - --runtime=python312
      - --timeout=60s
      - --project=bike-sharing-448504
      - --region=us-central1
      - --service-account=bss-sharing@bike-sharing-448504.iam.gserviceaccount.com
      - --source=.
      - --entry-point=process_csv
      - --trigger-event-filters=type=google.cloud.storage.object.v1.finalized
      - --trigger-event-filters=bucket=bss_data_raw

options:
  logging: CLOUD_LOGGING_ONLY
