steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - bss-etl
      # - --trigger-event=google.storage.object.finalize
      # - --trigger-resource=bss_data_raw
      - --runtime=python312
      - --trigger-http
      - --timeout=90
      - --entry-point=process_csv
      - --allow-unauthenticated
      - --service-account=bss-sharing@bike-sharing-448504.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
