steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - bss-etl
      - --gen2
      - --runtime=python312
      - --timeout=60s
      - --region=us-central1
      - --entry-point=process_csv
      - --trigger-event-filters=type=google.cloud.storage.object.v1.finalized
      - --trigger-event-filters=bucket=bss_data_raw
      - --memory=512Mi

options:
  logging: CLOUD_LOGGING_ONLY
